version: "3.7"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/sbakhit/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/sbakhit/data/mariadb

networks:
  inception:
    driver: bridge
