version: "3.7"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 443:443
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    env_file: 
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    env_file: 
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    environment:
      WP_ADMIN_USER: admin
      WP_ADMIN_EMAIL: admin@example.com
      WP_SITE_TITLE: "My Inception Site"
      WP_SITE_URL: "https://sbakhit.42.fr"
    secrets:
      - credentials
    networks:
      - inception
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/$USER/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/$USER/data/mariadb'

networks:
  inception:
    driver: bridge

secrets:
  credentials:
    file: ./secrets/credentials
