version: "3.7"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    env_file:
      - .env
    volumes:
      - ./data/wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    env_file:
      - .env
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    ports:
      - 3306:3306

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    env_file:
      - .env
    volumes:
      - ./data/wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

    

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sbakhit/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sbakhit/data/mariadb 