version: "3.9"

services:
  nginx:
    container_name: nginx
    image:  nginx
    build: requirements/nginx/
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always
    
  wordpress:
    container_name: wordpress
    image: wordpress
    build: requirements/wordpress/
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    restart: always
  redis:
    container_name: redis
    build: requirements/bonus/redis
    env_file:
      - .env
    networks:
      - inception
    restart: always
    volumes:
      - redis:/data 
    ports:
      - "6379:6379"
  ftp:
    container_name: 'ftp'
    build:
      context: ./requirements/ftp
      dockerfile: Dockerfile
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
    image: ftp
    restart: on-failure
    networks:
      - inception
    ports:
      - "${FTP_PORT:-21}:21"
      - "${FTP_PASSIVE_PORTS:-21100-21110}:21100-21110"
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - .env
    depends_on:
      - wordpress


networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/$USER/data/wordpress'

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/$USER/data/mariadb'

  redis:
    name: redis
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/$USER/data/redis'

